### ISSUE TITLE
Add a direct share to Telegram inside of

### ISSUE THREAD

**Issue by vonDubenshire** [corbindavenport/link-cleaner#17]
As Telegram has skyrocketed in use in the USA, it's my primary share choice on any thing I send.

One of my main reasons I looked for an app like this is because I use the Pixel Launcher search bar which opens the Google app to make a search.

In Android 12 and later, I could open the Recents overview menu and tap the link icon to share directly from the Google app instead of re-searching in Chrome when I wanted to send a search page link.

But the Google app tacked so much stuff it was giant URLs.

Your app kept me from needing that.

However after seeing all your other options to share directly to with, I thought I'd request a Telegram one. (and make the way so it worked universally not the old way that looks only for the specific app, as many use the Telegram PWA, desktop apps, web page, or non-Google Play versions.)

![Screenshot_20221208-183744](https://user-images.githubusercontent.com/40748193/206596102-8a8ea7b7-8e47-4c76-b938-8118c1495104.png)

**Comment by corbindavenport** [comment]
Sure, adding a Telegram share target isn't hard. Long-term there probably needs to be a better UI for all the share options, but that's a different issue.

**Comment by corbindavenport** [comment]
This is live now.
