### ISSUE TITLE
Strip shortened TikTok links to their canonical form.

### ISSUE THREAD

**Issue by Permik** [corbindavenport/link-cleaner#20]
When sharing links from TikTok, the app generates an unique link that is associated with your account.
For the privacy reasons of me and others I'd like an option to get rid of that.

This _could_ be out of the scope of this project, so please don't be afraid to close the issue :)

**Comment by corbindavenport** [comment]
Do you have an example of a shortened/unique and non-unique link? I'm not sure how possible that is without querying an API or something.

**Comment by corbindavenport** [comment]
It looks like a simple curl request or a `fetch()` in JavaScript reveals the real video URL:

```
corbin@Enterprise ~ % curl "https://www.tiktok.com/t/ZP81yQunW/"
<a href="https://www.tiktok.com/@funnycats0ftiktok/video/7395951284618071338?_t=8oxPVPxvQ6w&amp;_r=1">Moved Permanently</a>.

corbin@Enterprise ~ % 
```

However, TikTok has a CORS Same Origin Policy enabled on its website, so Link Cleaner wouldn't be able to query for that information without a proxy running on a web server somewhere (or paying for an API). I'm not able to implement that right now, so I'll close this.
