### ISSUE TITLE
Macy's Link

### ISSUE THREAD

**Issue by thomasclarkms** [corbindavenport/link-cleaner#21]
Links from Macy's lose their function because the link cleaner drops the ID .
https://www.macys.com/shop/product/anthony-veer-mens-roosevelt-ii-double-monk-strap-goodyear-welt-dress-shoe?ID=10920481&CategoryID=70405&sizes=MEN_SHOE_SIZE_T|DRESS_SHOE_TYPE!!11|Monk%20Strap&swatchColor=Red%20Red

becomes:
https://www.macys.com/shop/product/anthony-veer-mens-roosevelt-ii-double-monk-strap-goodyear-welt-dress-shoe
this link doesn't work.

This link works:
https://www.macys.com/shop/product/anthony-veer-mens-roosevelt-ii-double-monk-strap-goodyear-welt-dress-shoe?ID=10920481

**Comment by corbindavenport** [comment]
Thanks for reporting, the fix should be rolled out now :)
