### ISSUE TITLE
App doesn't work if settings are not checked at least the first time

### ISSUE THREAD

**Issue by Urban82** [corbindavenport/link-cleaner#27]
After the changes made in commit a268656b7d93803218dd8863e1541d4be00d184f, the app is not working anymore if the setting page is not open the first time and both checkboxes are flagged (and then unflagged) the first time.

The issue is in rows 24-25 in file js/main.js: without interacting the first time with the checkboxes, `getItem` returns a null value and the following `toLowerCase()` method will fail.

https://github.com/corbindavenport/link-cleaner/blob/a268656b7d93803218dd8863e1541d4be00d184f/js/main.js#L24-L25

The same issue should be present in file js/bulk.js on rows 8-9:

https://github.com/corbindavenport/link-cleaner/blob/a268656b7d93803218dd8863e1541d4be00d184f/js/bulk.js#L8-L9

**Comment by corbindavenport** [comment]
Thanks for letting me know, I've implemented a fix in https://github.com/corbindavenport/link-cleaner/commit/6d8608465f2e45993c5d021e7c2c48dd8ea287aa. The logic for checking those settings probably needs to go in `shared.js` anyway, I'll do that sometime soon.
