### ISSUE TITLE
Extract URLs from Text

### ISSUE THREAD

**Issue by silas229** [corbindavenport/link-cleaner#7]
When I share a tweet in the Twitter PWA, not only the link is shared but also the content:
> Corbin Davenport (@corbindavenport) Tweeted:
Check out my podcast @TechTalesShow, where me and a guest talk about wild stories in technology history, from early computers to mobile games.
> 
> YouTube: https://t.co/zCeEANnIhU
> 
> Apple: https://t.co/i5YVCpXGfG
> 
> Spotify: https://t.co/WPd90JFmQx
> 
> SoundCloud: https://t.co/uf9ii4h7Cc 
> https://twitter.com/corbindavenport/status/1468665663476617216?s=20&t=Cg4SWcxfa2AqONQ0lz5VLg 

Unfortunately, when I then select the Link Cleaner, it does not work. 

**My idea:** 
Either URLs should be extracted from the content or the text should be kept and the links replaced with clean links in it.

The best would be a selection in the PWA, where the user can choose one of these options

**Comment by corbindavenport** [comment]
This could actually plug into #4, I think. Once bulk link processing is implemented, Link Cleaner could just pass all links from the incoming text without any prompts or anything.

**Comment by silas229** [comment]
I can't follow the code in #8 completely because I am not aware of the full codebase, but it seems to extract/filter at least the URL

**Comment by corbindavenport** [comment]
Closing this because fixing Twitter/X behaviors isn't a priority, and I'm not aware of this happening with another Android application. If this is reported again with another app I'll look into it.
